```{r}
getwd()
setwd('E:/riii/final')
load('lvr_prices_big5.RData')
```

```{r}
str(lvr_prices)
```

```{r}
install.packages('dplyr')#原先有安裝dplyr套件則不需執行
library(dplyr)#引入dplyr套件
house = filter(lvr_prices,city_land_type =='住'& total_price > 0 & building_sqmeter > 0 & finish_ymd != "" )
```

```{r}
house = cbind(house,round(house$total_price/house$building_sqmeter))
colnames(house)[ncol(house)] = 'price_per_sqmeter'
```

```{r}
house = house[abs(scale(house$price_per_sqmeter)) <= 3,]
```

```{r}
summary(house$area)
barplot(table(house$area))
```

```{r}
tapply(house$price_per_sqmeter,house$area,mean)#各行政區每坪方米價格的平均數(解1)
tapply(house$price_per_sqmeter,house$area,median)#各行政區每坪方米價格的中位數(解1)
tapply(house$price_per_sqmeter,house$area,sd)#各行政區每坪方米價格的標準差(解1)


library(dplyr)##各行政區每坪方米價格的平均數(解2)
house %>%
  group_by(area) %>%
  summarise(price_per_sqmeter_mean = mean(price_per_sqmeter, na.rm=TRUE)) %>%
  arrange(desc(price_per_sqmeter_mean))



house %>%#各行政區每坪方米價格的中位數(解2)
  group_by(area) %>%
  summarise(price_per_sqmeter_median = median(price_per_sqmeter, na.rm=TRUE)) %>%
  arrange(desc(price_per_sqmeter_median))



house %>%#各行政區每坪方米價格的標準差(解2)
  group_by(area) %>%
  summarise(price_per_sqmeter_sd = sd(price_per_sqmeter, na.rm=TRUE)) %>%
  arrange(desc(price_per_sqmeter_sd))

```

```{r}
install.packages('ggplot2')#原先有安裝ggplot2套件則不需執行
library(ggplot2)#引入ggplot2套件
g = ggplot(house,aes(x=house$price_per_sqmeter))+geom_histogram()+facet_wrap(~house$area)
g
```

```{r}
house = cbind(house,as.integer(round((Sys.Date()-as.Date(house$finish_ymd))/365)))
colnames(house)[ncol(house)] = 'building_age'
```

```{r}
load('house_danger.RData')
house = merge(house_danger,house,by.x="ID",by.y="ID",all.x=TRUE)
```

```{r}
str(house)
house = house[,names(house) %in% c("danger","area","building_age","building_sqmeter","building_type","price_per_sqmeter")]
set.seed(1206)
ind = sample(2,nrow(house),replace = TRUE,prob=c(0.8,0.2))
trainset = house[ind ==1,]
testset = house[ind ==2,]

```

```{r}
library(rpart)
house.rp = rpart(danger~.,data=trainset)
```

```{r}
plot(house.rp,margin=0.1)
text(house.rp,all=TRUE,use.n=TRUE)
```

```{r}
summary(house.rp)
```

```{r}
library(caret)
predictions = predict(house.rp,testset,type="class")
table(predictions,testset$danger)
confusionMatrix(table(predictions,testset$danger))
```

```{r}
#install.packages("ROCR")
library(ROCR)
predictions <-predict(house.rp, testset, type="prob")
head(predictions)
pred.to.roc<-predictions[, 2]
head(pred.to.roc)
pred.rocr<-prediction(pred.to.roc,testset$danger)
pred.rocr
perf.rocr<-performance(pred.rocr, measure ="auc")
perf.tpr.rocr<-performance(pred.rocr, measure="tpr",x.measure = "fpr")
plot(perf.tpr.rocr,main=paste("AUC:",(perf.rocr@y.values)))
```
